{% set version = "0.3.6.dev0" %}

package:
    name: gevent-socketio
    version: {{ version }}

source:
    git_url: https://github.com/abourget/gevent-socketio
    git_tag: 8971328ab467adc49bec98bc9eb7d13c89d9dac6
    patches:
        - remove-versiontools.patch

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
    build:
        - python
        - setuptools
        - gevent >=1.1rc5
        - gevent-websocket
        - six
    run:
        - python
        - gevent >=1.1rc5
        - gevent-websocket
        - six

test:
    imports:
        - socketio

about:
    home: https://github.com/abourget/gevent-socketio
    license: BSD
    summary: 'SocketIO server based on the Gevent pywsgi server, a Python network library'

extra:
    recipe-maintainers:
        - daf
